site_name:        GraphsFlows.jl
repo_url:         https://github.com/JuliaGraphs/GraphsFlows.jl
site_description: Documentation for GraphsFlows, the JuliaGraphs package for flow and cut problems
site_author:      JuliaGraphs

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
